#!/usr/bin/env python3
# Single-source help generator: HelpBook/topics/*.md becomes the in-app
# content (Plumage/Help/HelpTopic+Content.swift) and the Apple Help Book
# (HTML + hiutil index). Run manually after edits; outputs are committed.

import html
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TOPICS_DIR = REPO / "HelpBook" / "topics"
SWIFT_OUT = REPO / "Plumage" / "Help" / "HelpTopic+Content.swift"
LPROJ = REPO / "Plumage" / "HelpBook" / "Plumage.help" / "Contents" / "Resources" / "en.lproj"

SECTION_ORDER = ["The App", "Templates", "Bundled Defaults"]
SWIFT_INDENT = " " * 12
SWIFT_WRAP = 104


def parse_topic(path):
    text = path.read_text(encoding="utf-8")
    parts = text.split("---\n", 2)
    if len(parts) < 3 or parts[0].strip():
        sys.exit(f"{path.name}: expected leading frontmatter block")
    meta = {}
    for line in parts[1].strip().splitlines():
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip()
    for key in ("id", "swift", "title", "icon", "section"):
        if not meta.get(key):
            sys.exit(f"{path.name}: missing frontmatter key '{key}'")
    if meta["section"] not in SECTION_ORDER:
        sys.exit(f"{path.name}: unknown section '{meta['section']}'")
    body = parts[2].strip("\n")
    if "\\" in body or '"""' in body:
        sys.exit(f"{path.name}: body must not contain backslashes or triple quotes")
    return meta, body


def slug(title):
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")


# --- Swift emission ---


def wrapped_swift_lines(body):
    out = []
    in_fence = False
    for line in body.split("\n"):
        if line.startswith("```"):
            in_fence = not in_fence
        if not line:
            out.append("")
            continue
        if in_fence or line.startswith("```"):
            if len(SWIFT_INDENT + line) > 118:
                sys.exit(f"fence line too long for the 120-column limit: {line[:60]}…")
            out.append(SWIFT_INDENT + line)
            continue
        words = line.split(" ")
        chunk = ""
        chunks = []
        for word in words:
            candidate = word if not chunk else f"{chunk} {word}"
            if len(candidate) > SWIFT_WRAP and chunk:
                chunks.append(chunk)
                chunk = word
            else:
                chunk = candidate
        chunks.append(chunk)
        for index, part in enumerate(chunks):
            cont = " \\" if index < len(chunks) - 1 else ""
            out.append(f"{SWIFT_INDENT}{part}{cont}")
    return out


def swift_topic(meta, body):
    lines = [
        f"    static let {meta['swift']} = HelpTopic(",
        f'        id: "{meta["id"]}",',
        f'        title: "{meta["title"]}",',
        f'        systemImage: "{meta["icon"]}",',
        '        markdown: """',
    ]
    lines += wrapped_swift_lines(body)
    lines += ['            """', "    )"]
    return "\n".join(lines)


def swift_sections(topics):
    lines = ["    static let sections: [HelpSection] = ["]
    for section in SECTION_ORDER:
        members = [t for t in topics if t[0]["section"] == section]
        if not members:
            continue
        lines += [
            "        HelpSection(",
            f'            id: "{slug(section)}",',
            f'            title: "{section}",',
        ]
        # swift-format collapses single-element literals to one line, where a
        # trailing comma is a lint error — emit those inline from the start.
        if len(members) == 1:
            lines.append(f"            topics: [.{members[0][0]['swift']}]")
        else:
            lines.append("            topics: [")
            lines += [f"                .{meta['swift']}," for meta, _ in members]
            lines.append("            ]")
        lines.append("        ),")
    lines.append("    ]")
    return "\n".join(lines)


def write_swift(topics):
    blocks = [swift_topic(meta, body) for meta, body in topics]
    blocks.append(swift_sections(topics))
    joined = "\n\n".join(blocks)
    write_if_changed(
        SWIFT_OUT,
        "import Foundation\n\n"
        "// Generated by HelpBook/generate.py from HelpBook/topics — do not edit\n"
        "// here; change a topic source and re-run the generator.\n"
        f"extension HelpTopic {{\n{joined}\n}}\n",
    )


# --- HTML emission ---


def inline_html(text):
    escaped = html.escape(text, quote=False)
    codes = []

    def stash(match):
        codes.append(f"<code>{match.group(1)}</code>")
        return f"\x00{len(codes) - 1}\x00"

    escaped = re.sub(r"`([^`]+)`", stash, escaped)
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", escaped)
    return re.sub(r"\x00(\d+)\x00", lambda m: codes[int(m.group(1))], escaped)


def table_html(rows):
    head = [inline_html(cell) for cell in split_cells(rows[0])]
    out = ["<table>", "<thead><tr>"]
    out += [f"<th>{cell}</th>" for cell in head]
    out += ["</tr></thead>", "<tbody>"]
    for row in rows[2:]:
        out.append("<tr>" + "".join(f"<td>{inline_html(c)}</td>" for c in split_cells(row)) + "</tr>")
    out += ["</tbody>", "</table>"]
    return out


def split_cells(row):
    return [cell.strip() for cell in row.strip().strip("|").split("|")]


ORDERED_ITEM = re.compile(r"^\d+\. ")


def body_html(body):
    out = []
    lines = body.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("```"):
            fence = []
            i += 1
            while i < len(lines) and not lines[i].startswith("```"):
                fence.append(html.escape(lines[i], quote=False))
                i += 1
            i += 1
            out.append("<pre><code>" + "\n".join(fence) + "</code></pre>")
            continue
        if line.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].startswith("|"):
                rows.append(lines[i])
                i += 1
            out += table_html(rows)
            continue
        if line.startswith("- "):
            out.append("<ul>")
            while i < len(lines) and lines[i].startswith("- "):
                out.append(f"<li>{inline_html(lines[i][2:])}</li>")
                i += 1
            out.append("</ul>")
            continue
        if ORDERED_ITEM.match(line):
            out.append("<ol>")
            while i < len(lines) and ORDERED_ITEM.match(lines[i]):
                out.append(f"<li>{inline_html(ORDERED_ITEM.sub('', lines[i]))}</li>")
                i += 1
            out.append("</ol>")
            continue
        heading = re.match(r"^(#{1,6}) (.+)$", line)
        if heading:
            level = len(heading.group(1))
            out.append(f"<h{level}>{inline_html(heading.group(2))}</h{level}>")
        elif line.strip():
            out.append(f"<p>{inline_html(line)}</p>")
        i += 1
    return "\n".join(out)


def page_html(title, content, apple_title=None):
    meta = f'\n<meta name="AppleTitle" content="{apple_title}">' if apple_title else ""
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8">'
        f"{meta}\n"
        f"<title>{html.escape(title, quote=False)}</title>\n"
        '<link rel="stylesheet" href="style.css">\n'
        "</head>\n"
        "<body>\n"
        f"{content}\n"
        "</body>\n"
        "</html>\n"
    )


STYLE = """\
:root { color-scheme: light dark; }
body {
    font-family: -apple-system, "Helvetica Neue", sans-serif;
    line-height: 1.5;
    max-width: 42em;
    margin: 2em auto;
    padding: 0 1.5em;
}
nav { margin-bottom: 1.5em; font-size: 0.9em; }
code, pre {
    font-family: ui-monospace, Menlo, monospace;
    font-size: 0.9em;
    background: rgba(127, 127, 127, 0.12);
    border-radius: 4px;
}
code { padding: 0.1em 0.3em; }
pre { padding: 0.8em 1em; overflow-x: auto; }
pre code { background: none; padding: 0; }
table { border-collapse: collapse; margin: 1em 0; }
th, td { border: 1px solid rgba(127, 127, 127, 0.35); padding: 0.35em 0.8em; text-align: left; }
"""


# The hiutil index is not byte-stable across runs, so it is rebuilt only when
# page content actually changed — a no-op run must leave the repo clean.
def write_if_changed(path, text):
    data = text.encode("utf-8")
    if path.exists() and path.read_bytes() == data:
        return False
    path.write_bytes(data)
    return True


def write_help_book(topics):
    LPROJ.mkdir(parents=True, exist_ok=True)
    changed = False
    expected = {f"{meta['id']}.html" for meta, _ in topics} | {"index.html"}
    for stale in LPROJ.glob("*.html"):
        if stale.name not in expected:
            stale.unlink()
            changed = True
    changed |= write_if_changed(LPROJ / "style.css", STYLE)
    for meta, body in topics:
        nav = '<nav><a href="index.html">Plumage Help</a></nav>\n'
        content = nav + body_html(body)
        changed |= write_if_changed(LPROJ / f"{meta['id']}.html", page_html(meta["title"], content))
    sections_html = ["<h1>Plumage Help</h1>"]
    for section in SECTION_ORDER:
        members = [meta for meta, _ in topics if meta["section"] == section]
        if not members:
            continue
        sections_html.append(f"<h2>{html.escape(section, quote=False)}</h2>")
        sections_html.append("<ul>")
        sections_html += [
            f'<li><a href="{meta["id"]}.html">{html.escape(meta["title"], quote=False)}</a></li>'
            for meta in members
        ]
        sections_html.append("</ul>")
    index = page_html("Plumage Help", "\n".join(sections_html), apple_title="Plumage Help")
    changed |= write_if_changed(LPROJ / "index.html", index)
    index_path = LPROJ / "Plumage.helpindex"
    if changed or not index_path.exists():
        subprocess.run(
            ["/usr/bin/hiutil", "-Cf", str(index_path), str(LPROJ)],
            check=True,
        )


def main():
    paths = sorted(TOPICS_DIR.glob("*.md"))
    if not paths:
        sys.exit("no topic sources found")
    topics = [parse_topic(path) for path in paths]
    write_swift(topics)
    write_help_book(topics)
    print(f"generated {len(topics)} topics -> {SWIFT_OUT.relative_to(REPO)}, {LPROJ.relative_to(REPO)}")


if __name__ == "__main__":
    main()
