import Foundation

// Generated by HelpBook/generate.py from HelpBook/topics — do not edit
// here; change a topic source and re-run the generator.
extension HelpTopic {
    static let howPlumageWorks = HelpTopic(
        id: "how-plumage-works",
        title: "How Plumage Works",
        systemImage: "info.circle",
        markdown: """
            # How Plumage Works

            Plumage is a native macOS front end for Claude Code workflows: issues on a Kanban board, an embedded \
            agent session, an integrated editor and a local PR view.

            ## The bundled setup is optional

            Plumage ships with a complete setup: a plan/implement/review workflow, project templates, hooks and \
            skills. None of it is mandatory. Everything under `.claude/` is plain files scaffolded from templates \
            you control. The workflow buttons run commands you can edit per project. Use the bundled workflow as it \
            is or replace any part of it with your own. The "Bundled Defaults" section covers what ships in the box; \
            everything else in this help, including the template system, describes the app itself and applies no \
            matter how you set things up.

            ## Files are the source of truth

            Plumage stores nothing in a database. Everything lives in plain files inside your project:

            - `.claude/` holds issues, docs, hooks and skills. These are the same files Claude Code reads.
            - `<name>.plumage` is a bundle in your project folder with Plumage's own metadata: project \
            configuration, run state and session bookkeeping.

            Plain-file state survives crashes and restarts. Git versions it like source code. When something looks \
            wrong, any text editor will do.

            ## Local by design

            The workflow ends at "merged locally". Plumage never pushes on its own and never opens pull requests. \
            The PR view is a local artifact rendered from the issue's `pr.md`. With a connected GitHub account, \
            pushing and pulling are still manual actions.

            ## Claude runs as a subprocess

            All Claude interaction goes through the `claude` command-line tool installed on your Mac. It is the same \
            Claude Code you would run in a terminal, with the same login. Plumage never calls the Anthropic API \
            directly, so a Claude Pro or Max subscription works the same way it does in a terminal session.
            """
    )

    static let issuesAndBoard = HelpTopic(
        id: "issues-and-board",
        title: "Issues & the Board",
        systemImage: "rectangle.split.3x1",
        markdown: """
            # Issues & the Board

            Issues live in `.claude/issues/<id>-<slug>/spec.md`. The spec's frontmatter is the source of truth; the \
            board is a view of those files.

            ## Statuses and columns

            An issue is in one of six statuses: `draft`, `approved`, `in-progress`, `waiting-for-review`, `done` or \
            `blocked`.

            The board shows four columns:

            | Column | Statuses |
            | --- | --- |
            | Todo | `draft`, `approved`, `blocked` |
            | In Progress | `in-progress` |
            | Waiting for Review | `waiting-for-review` |
            | Done | `done` |

            Draft, approved and blocked issues share the Todo column; look at the card's status badge to tell them \
            apart.

            ## Who moves an issue

            The `status:` field is ordinary spec frontmatter. Like the rest of the file, it belongs to you. With the \
            bundled workflow the skills manage it: Plan flips `draft` to `approved`, Implement moves through \
            `in-progress` to `waiting-for-review` and the app's Merge action flips a merged issue to `done`. If you \
            run your own workflow, edit `status:` however you like. The board follows the file.

            ## Issue types

            Each issue has a type, configurable in Settings > Issue Types. A type's "draft blocks implement" flag \
            decides whether an issue must be planned before the Implement button enables. By default only features \
            require planning; chores, spikes and refactors can go straight from draft to Implement.
            """
    )

    static let mergingIssues = HelpTopic(
        id: "merging-issues",
        title: "Merging Issues",
        systemImage: "arrow.triangle.merge",
        markdown: """
            # Merging Issues

            Merging happens in the Merge section of an issue in review. It is a local operation; Plumage neither \
            pushes nor opens a pull request.

            ## Squash by default

            The default mode squashes the issue branch into a single commit on the target branch, one commit per \
            issue. The per-task checkpoint commits stay behind on the issue branch. Fast-forward mode is available \
            when the target branch has no commits the issue branch lacks.

            ## The squash subject

            The commit subject is prefilled from the spec's `mergeSubject` frontmatter field (falling back to the \
            issue title) and can be edited before merging. The bundled workflow's convention is an imperative \
            one-liner describing the change, without issue id, slug or merge mechanics like "squash". The Merge \
            button stays disabled while the subject is empty.

            ## Guards and rollback

            Before merging, Plumage checks that the working tree is clean and that no implement run is active in the \
            checkout. After a successful merge the issue's status flips to `done`. If anything fails mid-merge, \
            Plumage rolls back and returns to the branch you were on.

            ## Rebase & Merge

            When fast-forward is impossible because the target branch has moved on, a Rebase & Merge action appears. \
            It rebases the issue branch onto the target. On a conflict it aborts automatically and leaves the branch \
            unchanged for manual resolution.

            ## Branch cleanup

            "Delete branch after merge" is on by default. After a squash, git considers the branch unmerged, so \
            Plumage force-deletes it. This is safe because the merge just landed its content. If the branch is \
            checked out in another worktree, a clean worktree is removed along with it; a dirty worktree keeps both \
            and shows a warning instead.

            ## Merge target

            The target branch is selectable per project and remembered in the `.plumage` bundle \
            (`merge-target.json`).
            """
    )

    static let archivingIssues = HelpTopic(
        id: "archiving-issues",
        title: "Archiving Issues",
        systemImage: "archivebox",
        markdown: """
            # Archiving Issues

            Archiving moves a finished issue off the board without deleting anything.

            ## How it works

            Archiving moves the issue's whole folder from `.claude/issues/<id>-<slug>/` to \
            `.claude/issues/archive/<id>-<slug>/`. Nothing is rewritten; spec, docs and PR file travel as-is. If a \
            folder with the same name already exists in the archive, a numeric suffix is appended.

            ## The Archive view

            The Archive entry in the sidebar lists archived issues read-only. Unarchive an issue from its context \
            menu and the folder moves straight back to `.claude/issues/`, where the issue reappears on the board.

            Archiving is always a manual action. Finishing or merging an issue never archives it automatically.
            """
    )

    static let sessionsAndUsage = HelpTopic(
        id: "sessions-and-usage",
        title: "Sessions & Usage",
        systemImage: "gauge.medium",
        markdown: """
            # Sessions & Usage

            ## Usage pill

            The status bar can show a compact usage pill next to the session indicator; click it for the full \
            breakdown. Configure it in Settings > Usage: the pill itself, the 5-hour window and the 7-day window \
            toggle independently. By default the pill and the 5-hour window are on; the 7-day window is off.

            ## Keeping the Mac awake

            "Keep Mac awake during sessions" in Settings > General (off by default) prevents system idle sleep while \
            any Claude session is live. That covers the embedded session as well as sessions running in terminal \
            tabs. Only system sleep is held off; the display may still sleep. Once no session is live, normal sleep \
            behavior returns.
            """
    )

    static let templatesAndScaffolding = HelpTopic(
        id: "templates-and-scaffolding",
        title: "Templates & Scaffolding",
        systemImage: "doc.text",
        markdown: """
            # Templates & Scaffolding

            New projects are scaffolded from templates. Three tiers stack, from least to most specific: **Base < \
            Component < Template**. A more specific tier refines the tiers below it.

            The bundled templates lean Swift and Xcode, but nothing ties the template system to that stack. You can \
            override any bundled file or add your own. A template can target whatever stack or workflow you have in \
            mind. Even the bundled workflow skills arrive through templates; replace them and every new project \
            starts differently.

            ## What templates provide

            Templates contribute hooks, skills, docs, agents and arbitrary files or folders. Typed items land in \
            their fixed category folder (`hooks/`, `skills/`, `docs/`, `agents/`); plain files and folders are \
            placed wherever the template puts them.

            ## Customizing

            Settings > Templates and the Template Manager (⇧⌘T) let you override any bundled file or add your own. \
            Overrides are stored per file in Application Support rather than inside your project, so a new scaffold \
            always starts from your current template state.

            - A dot marker (●) means an override actually differs from the bundled file.
            - **Reset to default** restores a bundled-backed file; **Delete** removes a user-authored one.
            - Bundled files cannot be deleted from disk, so removing one places a tombstone that hides it from \
            scaffolding.
            - **Restore Defaults** moves the whole override store to the Trash, so the step is recoverable.

            ## Same-named files merge

            When the same file name appears in more than one tier, the variants are composed into a single output \
            file instead of the most specific one silently winning. How they compose depends on the file; see \
            Template Merge Syntax.
            """
    )

    static let templateMergeSyntax = HelpTopic(
        id: "template-merge-syntax",
        title: "Template Merge Syntax",
        systemImage: "chevron.left.forwardslash.chevron.right",
        markdown: """
            # Template Merge Syntax

            When template tiers contribute a file with the same name, Plumage merges the variants into one output \
            file. The strategy is chosen in this order:

            1. **Placeholder merge** whenever the least-specific variant contains `<<<keyword>>>` placeholder lines, \
            regardless of file extension.
            2. **Format-aware merge** by extension: `.json`, `.xml`, `.md` / `.markdown`.
            3. **Plain-text append** for any other text file.
            4. **Copy** for binary files and for variants a merge cannot parse. The most specific variant wins \
            verbatim.

            Merged output keeps the most specific variant's permissions, so scripts stay executable.

            ## Placeholder merge

            The least-specific file (the skeleton) marks insertion points with a placeholder alone on its own line:

            ```
            ## Reference docs
            <<<refdocs>>>
            ```

            Any contributing variant fills a placeholder with a matching block:

            ```
            %% refdocs %%
            - docs/PROJECT.md — what this project is
            %% /refdocs %%
            ```

            Rules:

            - Matching is exact and case-sensitive: `<<<refdocs>>>` is filled only by `%% refdocs %%`, never by `%% \
            Refdocs %%` or `%% ref docs %%`.
            - Markers must stand alone on their line; whitespace around the keyword inside the markers is ignored.
            - Several blocks with the same keyword, in one file or across tiers, join in source order separated by a \
            blank line.
            - Unfilled placeholders are dropped from the output. If the dropped placeholder sat directly under a `## \
            ` heading, the heading is removed too, so an empty section leaves no orphan.
            - An unclosed `%% keyword %%` or a stray `%% /keyword %%` is an authoring error.

            ## Markdown: merge by heading

            Without placeholders, `.md` files merge section-wise:

            - Sections match on the exact heading line, level included: `## Build and test` only matches `## Build \
            and test`, never `# Build and test`.
            - A repeated heading fuses the contribution's leading block (up to its first blank line) into the \
            existing section; lines the section already contains are skipped.
            - New headings append at the end of the document.
            - YAML frontmatter is never line-merged; the most specific variant's frontmatter wins wholesale.
            - Fenced code blocks move and deduplicate as one unit. They are never split.

            ## JSON: deep merge

            - Objects merge key by key; the more specific variant wins on conflicts.
            - Arrays append elements that are not already present (deep value equality).
            - Expect a regenerated file rather than a byte-for-byte edit: output is re-serialized pretty-printed \
            with sorted keys.
            - If any variant fails to parse, no merge happens and the most specific variant is copied verbatim.

            ## XML: structural merge

            - All variants must share the root element name; otherwise the most specific variant is copied verbatim.
            - Attributes replace by name.
            - A child element whose name is unique on both sides merges recursively; other children append unless a \
            structurally identical one already exists.
            - Output is re-serialized pretty-printed.

            ## Plain text: append

            Text files with no better strategy concatenate in tier order, one blank line between chunks. A variant \
            identical to an earlier one is skipped, so a copied and untouched file never doubles its content.
            """
    )

    static let bundledWorkflow = HelpTopic(
        id: "bundled-workflow",
        title: "The Bundled Workflow",
        systemImage: "checklist",
        markdown: """
            # The Bundled Workflow

            Plumage ships a ready-made issue workflow: plan a spec, implement it task by task, review the result. \
            Every piece of it can be reconfigured or replaced.

            ## The three buttons

            The Plan, Implement and Review buttons on an issue start a Claude session with a configurable command. \
            Out of the box they run the bundled skills:

            | Button | Default command | Permission mode |
            | --- | --- | --- |
            | Plan | `/plumage-plan` | Plan Mode |
            | Implement | `/plumage-implement` | Accept Edits |
            | Review | `/plumage-review` | Default |

            Project settings let you edit each command (with `<slug>`, `<prompt>` and `<spec>` placeholders and \
            per-issue-type `#if` branches), change its permission mode and pick a model and effort per workflow. The \
            buttons launch whatever workflow you point them at.

            ## What the bundled Implement does

            The bundled implement skill works through the spec task by task on the issue's own branch, committing a \
            checkpoint after each task. Every commit must pass a pre-commit gate. In the bundled Swift setup that \
            means a warning-free build, green tests, clean SwiftLint and clean swift-format. The gate script is a \
            file in your project and evolves with your stack.

            The skill does not merge, push or archive. Those remain your explicit actions.

            ## Branches

            Each issue works on its own branch, named `issue/<slug>` by default. The prefix and the default target \
            branch are configurable in the project's `config.json` (`git.branchPrefix`, `git.defaultBranch`).

            ## Parallel runs

            Builds and tests run strictly serially across all worktrees; a "waiting for gate lock" line in a run is \
            normal queueing rather than an error. Two implement runs can execute in parallel only in separate git \
            worktrees. Starting a second run in the same checkout queues it first-in-first-out behind the active \
            one.

            Run state lives in the `.plumage` bundle (`runs/`), so an interrupted run can be resumed after a crash \
            or restart.

            ## Make it yours

            The skills behind the default commands are plain files in your project's `.claude/skills/`. Edit them \
            there or override the templates that scaffold them to change what future projects start with (see \
            Templates & Scaffolding).
            """
    )

    static let sections: [HelpSection] = [
        HelpSection(
            id: "the-app",
            title: "The App",
            topics: [
                .howPlumageWorks,
                .issuesAndBoard,
                .mergingIssues,
                .archivingIssues,
                .sessionsAndUsage,
            ]
        ),
        HelpSection(
            id: "templates",
            title: "Templates",
            topics: [
                .templatesAndScaffolding,
                .templateMergeSyntax,
            ]
        ),
        HelpSection(
            id: "bundled-defaults",
            title: "Bundled Defaults",
            topics: [.bundledWorkflow]
        ),
    ]
}
