import Foundation
import Testing

@testable import Plumage

@Suite("Sparkle integration")
struct SparkleIntegrationTests {
    @Test("Info.plist carries the four Sparkle keys with expected values")
    func infoPlistKeys() throws {
        let info = try #require(Bundle.main.infoDictionary)
        #expect(
            info["SUFeedURL"] as? String
                == "https://benjaminhuebner.com/apps/plumage/appcast.xml"
        )
        // The public key value is project-specific (generated by generate_keys);
        // assert only that it is present and non-empty.
        let publicKey = try #require(info["SUPublicEDKey"] as? String)
        #expect(!publicKey.isEmpty)
        #expect(info["SUEnableAutomaticChecks"] as? Bool == true)
        #expect(info["SUAutomaticallyUpdate"] as? Bool == false)
    }

    @MainActor
    @Test("UpdaterModel constructs without starting scheduled network checks")
    func updaterModelInitSmoke() {
        let model = UpdaterModel(startingUpdater: false)
        #expect(model.canCheckForUpdates == false)
    }
}
